package eco.app.panel;

import eco.app.interfaces.ManagementPanelAction;
import java.util.List;

import javax.swing.table.DefaultTableModel;

import eco.app.dao.EmployeeDao;
import eco.app.entity.Employee;
import eco.app.entity.EntityHelper;
import eco.app.helper.MessageHelper;
import eco.app.helper.NavigationHelper;
import eco.app.helper.SaveData;
import eco.app.helper.ShareData;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Lenovo
 */
public class EmployeePanel extends javax.swing.JPanel implements ManagementPanelAction<Employee> {

    /**
     * Creates new form EmployeePanel
     */
    private NavigationHelper nav;
    private DefaultTableModel tblModel;
    private List<Employee> employees;
    private int idEmployeeSelected = -1;

    public EmployeePanel() {
        initComponents();

        init();
    }

    public void init() {
        // And child panel
        setLayout(new MigLayout("fill", "0[]10[]0", "0[]0"));
        add(pnEmployeeForm, "w 38%, h 100%");
        add(pnEmployeeList, "w 62%, h 100%");

        // Initialize navigation helper
        nav = new NavigationHelper(btnNew, btnInsert, btnUpdate, btnDelete);

        // Get table model
        tblModel = (DefaultTableModel) tblEmployees.getModel();
        fillTable();
    }

    @Override
    public void addTableRow(Employee emp) {
        tblModel.addRow(EntityHelper.getData(emp,

                "id",
                "fullname",
                "phone",
                "email",
                "soldOut",
                "salary"

        ));
    }

    @Override
    public void fillTable() {
        try {
            tblModel.setRowCount(0);

            employees = new EmployeeDao().getAll();

            for (Employee employee : employees) {
                addTableRow(employee);
            }
        } catch (Exception e) {
            MessageHelper.showException(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnEmployeeList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployees = new eco.app.myswing.TableCustom();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFind = new eco.app.myswing.TextFieldCustom();
        cbByFullname = new eco.app.myswing.CheckBoxCustom();
        cbById = new eco.app.myswing.CheckBoxCustom();
        buttonRandius1 = new eco.app.myswing.ButtonRandius();
        pnEmployeeForm = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFullname = new eco.app.myswing.TextFieldCustom();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtUsername = new eco.app.myswing.TextFieldCustom();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtPassword = new eco.app.myswing.TextFieldCustom();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        rdoMale = new javax.swing.JRadioButton();
        rdoFemale = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtEmail = new eco.app.myswing.TextFieldCustom();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPhone = new eco.app.myswing.TextFieldCustom();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtAddress = new eco.app.myswing.TextFieldCustom();
        jPanel9 = new javax.swing.JPanel();
        btnNew = new eco.app.myswing.ButtonRandius();
        btnInsert = new eco.app.myswing.ButtonRandius();
        btnUpdate = new eco.app.myswing.ButtonRandius();
        btnDelete = new eco.app.myswing.ButtonRandius();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        spNote = new javax.swing.JScrollPane();
        txtNote = new javax.swing.JTextArea();
        btngGender = new javax.swing.ButtonGroup();

        pnEmployeeList.setBackground(SaveData.BG_CONTENT);

        tblEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Fullname", "Phone", "Email", "Sold out", "Salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployees);

        jPanel3.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Search:");

        txtFind.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        cbByFullname.setSelected(true);
        cbByFullname.setText("Fullname");
        cbByFullname.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        cbById.setText("ID");
        cbById.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        buttonRandius1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eco/app/icon/icons8_sync_25px.png"))); // NOI18N
        buttonRandius1.setText("Reload");
        buttonRandius1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonRandius1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRandius1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(cbByFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRandius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(cbByFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbById, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonRandius1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnEmployeeListLayout = new javax.swing.GroupLayout(pnEmployeeList);
        pnEmployeeList.setLayout(pnEmployeeListLayout);
        pnEmployeeListLayout.setHorizontalGroup(
            pnEmployeeListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmployeeListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnEmployeeListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnEmployeeListLayout.setVerticalGroup(
            pnEmployeeListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEmployeeListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnEmployeeForm.setBackground(SaveData.BG_CONTENT);

        jLabel2.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Create New Employee");

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 15, 1, 15));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(7, 0, 0, 10));

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setText("Fullname: ");
        jLabel4.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel4.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel4.add(jLabel4, java.awt.BorderLayout.LINE_START);

        txtFullname.setCanEmpty(false);
        txtFullname.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtFullname.setValidateAction(ShareData.validateAction);
        jPanel4.add(txtFullname, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setText("Username: ");
        jLabel10.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel10.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel12.add(jLabel10, java.awt.BorderLayout.LINE_START);

        txtUsername.setCanEmpty(false);
        txtUsername.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtUsername.setRegex("[^~]+");
        txtUsername.setValidateAction(ShareData.validateAction);
        jPanel12.add(txtUsername, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel12);

        jPanel13.setOpaque(false);
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel11.setText("Password:");
        jLabel11.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel11.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel13.add(jLabel11, java.awt.BorderLayout.LINE_START);

        txtPassword.setCanEmpty(false);
        txtPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPassword.setRegex("[^~]+");
        txtPassword.setValidateAction(ShareData.validateAction);
        jPanel13.add(txtPassword, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel13);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Gender:");
        jLabel5.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel5.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel5.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.GridLayout(1, 0));

        btngGender.add(rdoMale);
        rdoMale.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        rdoMale.setSelected(true);
        rdoMale.setText("Male");
        rdoMale.setOpaque(false);
        jPanel10.add(rdoMale);

        btngGender.add(rdoFemale);
        rdoFemale.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        rdoFemale.setText("Female");
        rdoFemale.setOpaque(false);
        jPanel10.add(rdoFemale);

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Email:");
        jLabel6.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel6.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel6.add(jLabel6, java.awt.BorderLayout.LINE_START);

        txtEmail.setCanEmpty(false);
        txtEmail.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtEmail.setRegex("^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$");
        txtEmail.setValidateAction(ShareData.validateAction);
        jPanel6.add(txtEmail, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Phone:");
        jLabel7.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel7.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel7.add(jLabel7, java.awt.BorderLayout.LINE_START);

        txtPhone.setCanEmpty(false);
        txtPhone.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtPhone.setRegex("[0-9]{10}");
        txtPhone.setValidateAction(ShareData.validateAction);
        jPanel7.add(txtPhone, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Address:");
        jLabel8.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel8.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel8.add(jLabel8, java.awt.BorderLayout.LINE_START);

        txtAddress.setCanEmpty(false);
        txtAddress.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtAddress.setRegex("[^~]+");
        txtAddress.setValidateAction(ShareData.validateAction);
        jPanel8.add(txtAddress, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        btnNew.setText("New");
        btnNew.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });
        jPanel9.add(btnNew);

        btnInsert.setBackground(SaveData.BTN_SUCCESS);
        btnInsert.setText("Insert");
        btnInsert.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        jPanel9.add(btnInsert);

        btnUpdate.setBackground(SaveData.BTN_WARNING);
        btnUpdate.setText("Update");
        btnUpdate.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel9.add(btnUpdate);

        btnDelete.setBackground(SaveData.BTN_DANGER);
        btnDelete.setText("Delete");
        btnDelete.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel9.add(btnDelete);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.BorderLayout(10, 10));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Note:");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel9.setMaximumSize(new java.awt.Dimension(150, 17));
        jLabel9.setMinimumSize(new java.awt.Dimension(150, 17));
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel11.add(jLabel9, java.awt.BorderLayout.LINE_START);

        txtNote.setColumns(20);
        txtNote.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNote.setRows(5);
        spNote.setViewportView(txtNote);

        jPanel11.add(spNote, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout pnEmployeeFormLayout = new javax.swing.GroupLayout(pnEmployeeForm);
        pnEmployeeForm.setLayout(pnEmployeeFormLayout);
        pnEmployeeFormLayout.setHorizontalGroup(
            pnEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnEmployeeFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnEmployeeFormLayout.setVerticalGroup(
            pnEmployeeFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmployeeFormLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblEmployeesMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_tblEmployeesMouseClicked
        if (evt.getClickCount() == 2) {
            int indexSelected = tblEmployees.getSelectedRow();

            if (indexSelected == -1)
                return;

            idEmployeeSelected = (int) tblEmployees.getValueAt(indexSelected, 0);

            Employee employee = (Employee) EntityHelper.find(employees, idEmployeeSelected);

            fillForm(employee);

        }
    }

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNewActionPerformed
        clearForm();
    }

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {
        try {

            StringBuilder sb = new StringBuilder();

            Employee employee = readForm(sb);

            if (employee == null) {
                return;
            }

            EmployeeDao dao = new EmployeeDao();

            if (dao.insert(employee)) {
                MessageHelper.showMessage(this, "Insert new employee successfully!");
                clearForm();
            } else {
                MessageHelper.showErrorMessage(this, "Insert new employee failed!");
            }

        } catch (Exception e) {
            MessageHelper.showException(this, e);
        } finally {
            fillTable();
        }

    }

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateActionPerformed
        try {

            StringBuilder sb = new StringBuilder();

            Employee employee = readForm(sb);

            if (employee == null) {
                return;
            }

            EmployeeDao dao = new EmployeeDao();

            if (dao.update(employee)) {
                MessageHelper.showMessage(this, "Update employee successfully!");
                clearForm();
            } else {
                MessageHelper.showErrorMessage(this, "Update employee failed!");
            }

        } catch (Exception e) {
            MessageHelper.showException(this, e);
        } finally {
            fillTable();
        }
    }

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDeleteActionPerformed
        try {

            StringBuilder sb = new StringBuilder();

            Employee employee = readForm(sb);

            if (employee == null) {
                return;
            }

            EmployeeDao dao = new EmployeeDao();

            if (dao.delete(employee)) {
                MessageHelper.showMessage(this, "Delete employee successfully!");
                clearForm();
            } else {
                MessageHelper.showErrorMessage(this, "Delete employee failed!");
            }

        } catch (Exception e) {
            MessageHelper.showException(this, e);
        } finally {
            fillTable();
        }
    }

    private void buttonRandius1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonRandius1ActionPerformed
        fillTable();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eco.app.myswing.ButtonRandius btnDelete;
    private eco.app.myswing.ButtonRandius btnInsert;
    private eco.app.myswing.ButtonRandius btnNew;
    private eco.app.myswing.ButtonRandius btnUpdate;
    private javax.swing.ButtonGroup btngGender;
    private eco.app.myswing.ButtonRandius buttonRandius1;
    private eco.app.myswing.CheckBoxCustom cbByFullname;
    private eco.app.myswing.CheckBoxCustom cbById;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnEmployeeForm;
    private javax.swing.JPanel pnEmployeeList;
    private javax.swing.JRadioButton rdoFemale;
    private javax.swing.JRadioButton rdoMale;
    private javax.swing.JScrollPane spNote;
    private eco.app.myswing.TableCustom tblEmployees;
    private eco.app.myswing.TextFieldCustom txtAddress;
    private eco.app.myswing.TextFieldCustom txtEmail;
    private eco.app.myswing.TextFieldCustom txtFind;
    private eco.app.myswing.TextFieldCustom txtFullname;
    private javax.swing.JTextArea txtNote;
    private eco.app.myswing.TextFieldCustom txtPassword;
    private eco.app.myswing.TextFieldCustom txtPhone;
    private eco.app.myswing.TextFieldCustom txtUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean validateForm(StringBuilder sb) {

        if (sb == null) {
            sb = new StringBuilder();
        }

        txtFullname.check(sb, "Fullname is empty.\n");
        txtUsername.check(sb, "Username is empty.\n");
        txtPassword.check(sb, "Password is empty.\n");
        txtAddress.check(sb, "Address is empty.\n");
        txtPhone.check(sb, "Phone is empty.\n");
        txtEmail.check(sb, "Email is empty.\n");

        return sb.isEmpty();

    }

    @Override
    public void clearForm() {
        txtFullname.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtAddress.setText("");
        txtPhone.setText("");
        txtEmail.setText("");
        txtNote.setText("");
        rdoMale.setSelected(true);

        nav.isCreateMode();

        idEmployeeSelected = -1;
    }

    @Override
    public void fillForm(Employee employee) {
        idEmployeeSelected = employee.getId();
        txtFullname.setText(employee.getFullname());
        txtUsername.setText(employee.getUsername());
        txtPassword.setText(employee.getPassword());
        txtAddress.setText(employee.getAddress());
        txtPhone.setText(employee.getPhone());
        txtEmail.setText(employee.getEmail());
        txtNote.setText(employee.getNote());
        if (employee.isGender()) {
            rdoMale.setSelected(true);
        } else {
            rdoFemale.setSelected(true);
        }

        nav.isEditMode();
    }

    @Override
    public Employee readForm(StringBuilder sb) throws Exception {
        if (!validateForm(sb)) {
            MessageHelper.showErrorMessage(this, sb.toString());
            return null;
        }
        Employee employee = new Employee();

        employee.setId(idEmployeeSelected);
        employee.setFullname(txtFullname.getText());
        employee.setUsername(txtUsername.getText());
        employee.setPassword(txtPassword.getText());
        employee.setAddress(txtAddress.getText());
        employee.setPhone(txtPhone.getText());
        employee.setEmail(txtEmail.getText());
        employee.setNote(txtNote.getText());
        employee.setGender(rdoMale.isSelected());

        return employee;
    }
}
