package eco.app.panel;

import eco.app.dao.BillItemDao;
import eco.app.dao.OrderDao;
import eco.app.dao.VoucherDao;
import eco.app.entity.EntityHelper;
import eco.app.entity.Order;
import eco.app.entity.Product.BillItem;
import eco.app.entity.Voucher;
import eco.app.helper.MessageHelper;
import eco.app.helper.SaveData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Lenovo
 */
public class OrderPanel extends javax.swing.JPanel {

    private final MigLayout layout = new MigLayout("fill", "0[]10[]0", "0[]0");

    private List<Order> orders = new ArrayList<>();

    private DefaultTableModel tblModel;

    private int idSelected;
    
    /**
     * Creates new form OrderPanel
     */
    public OrderPanel() {
        initComponents();
        init();
    }

    private void init() {
        tblModel = (DefaultTableModel) tblOrder.getModel();

        setLayout(layout);

        add(pnOrderPreview, "w 38%, h 100%");
        add(pnListOrder, "w 62%, h 100%");
        fillTable();
    }

    private void addTableRow(Order order) {
        tblModel.addRow(EntityHelper.getData(order,
                "id",
                "customerId",
                "quantity",
                "total$",
                "timeCreate<time>"
        ));
    }

    private void fillTable() {
        try {
            orders = new OrderDao().getAll();

            for (Order order : orders) {
                addTableRow(order);
            }

        } catch (Exception e) {
            MessageHelper.showException(this, e);
        }
    }

    private void showOrderPreview(int id) {

        try {
            
            Order order = new OrderDao().findById(id);
            
            if (order != null) {
                billPanel.setOrder(order);
                
                if (order.getVoucherId() != 0) {
                    Voucher voucher = new VoucherDao().findById(order.getVoucherId());
                    
                    if (voucher != null) {
                        billPanel.setVoucher(voucher);
                    }
                }
                
                List<BillItem> billItems = new BillItemDao().getBillItemsByIdOrder(id);
                billPanel.setBillItems(billItems);
            }
            
            billPanel.reload();
            
            
        } catch (Exception e) {
            MessageHelper.showException(this, e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnListOrder = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new eco.app.myswing.TableCustom();
        pnOrderPreview = new javax.swing.JPanel();
        billPanel = new eco.app.panel.BillPanel();

        pnListOrder.setBackground(SaveData.BG_CONTENT
        );
        pnListOrder.setLayout(new java.awt.BorderLayout());

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer", "Quantity", "Total", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrderMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        pnListOrder.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnOrderPreview.setBackground(new java.awt.Color(153, 255, 0));

        javax.swing.GroupLayout pnOrderPreviewLayout = new javax.swing.GroupLayout(pnOrderPreview);
        pnOrderPreview.setLayout(pnOrderPreviewLayout);
        pnOrderPreviewLayout.setHorizontalGroup(
            pnOrderPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnOrderPreviewLayout.setVerticalGroup(
            pnOrderPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrderMouseClicked
        
        int index = tblOrder.getSelectedRow();
        
        idSelected = (int) tblOrder.getValueAt(index, 0);
        
        if (evt.getClickCount() == 2) {
           showOrderPreview(idSelected);
       } 
    }//GEN-LAST:event_tblOrderMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eco.app.panel.BillPanel billPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnListOrder;
    private javax.swing.JPanel pnOrderPreview;
    private eco.app.myswing.TableCustom tblOrder;
    // End of variables declaration//GEN-END:variables
}
