package eco.app.panel;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

import eco.app.dao.ProductDao;
import eco.app.entity.EntityHelper;
import eco.app.entity.Product;
import eco.app.event.LabelDateChooserAction;
import eco.app.helper.Convertor;
import eco.app.helper.MessageHelper;
import eco.app.interfaces.Statistic;
import eco.app.model.DateChooseGroup;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Lenovo
 */
public class StatisticProductPanel extends javax.swing.JPanel implements Statistic<Product> {

    /**
     * Creates new form StatisticProductPanel
     */
    DefaultTableModel tableModel;
    private List<Product> products;
    private List<ComboBoxItem> period = new ArrayList<>();

    public StatisticProductPanel() {
        initComponents();
        tableModel = (DefaultTableModel) tableCustom1.getModel();

        init();
        initEvent();
    }

    private void init() {

        // Get all product
        try {
            products = new ProductDao().getAll();
            fillTable(products);
        } catch (Exception e) {
            MessageHelper.showException(this, e);
        }

        // AddItem to ComboBox
        DefaultComboBoxModel<ComboBoxItem> model = new DefaultComboBoxModel<>();
        model.addElement(new ComboBoxItem(0, "Today"));
        model.addElement(new ComboBoxItem(-1, "1 day ago"));
        model.addElement(new ComboBoxItem(-2, "2 days ago"));
        model.addElement(new ComboBoxItem(-3, "3 days ago"));
        model.addElement(new ComboBoxItem(-7, "1 week ago"));
        model.addElement(new ComboBoxItem(-14, "2 weeks ago"));
        model.addElement(new ComboBoxItem(-30, "1 month ago"));
        model.addElement(new ComboBoxItem(-60, "2 months ago"));
        model.addElement(new ComboBoxItem(-90, "3 months ago"));
        model.addElement(new ComboBoxItem(-180, "6 months ago"));
        model.addElement(new ComboBoxItem(-365, "1 year ago"));
        model.addElement(new ComboBoxItem(-999999, "All time"));

        cbbPeriod.setModel(model);

    }

    @Override
    public void initEvent() {
        dcFrom.addEvent((selectedDate) -> {
            Date from = selectedDate;
            Date to = dcTo.getSelectedDate();

            if (to != null) {
                filter(from, to);
            }
        });

        dcTo.addEvent((selectedDate) -> {
            Date from = dcFrom.getSelectedDate();
            Date to = selectedDate;

            if (from != null) {
                filter(from, to);
            }
        });

        cbbPeriodActionPerformed(null);
    }

    @Override
    public void filter(Date from, Date to) {

        System.out.println("From: " + Convertor.formatDateTime(from));
        System.out.println("To: " + Convertor.formatDateTime(to));

        try {
            products = new ProductDao().getByDate(from, to);
            fillTable(products);
        } catch (Exception e) {
            MessageHelper.showException(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDateChooser1 = new eco.app.myswing.LabelDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustom1 = new eco.app.myswing.TableCustom();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dcFrom = new eco.app.myswing.LabelDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dcTo = new eco.app.myswing.LabelDateChooser();
        jPanel2 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        cbbPeriod = new eco.app.myswing.ComboBoxCustom();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblTotalSoldOut = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblIncome = new javax.swing.JLabel();

        setOpaque(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout(0, 10));

        tableCustom1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Import price", "Sold out", "Profit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCustom1);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout(15, 0));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("From");
        jPanel6.add(jLabel1, java.awt.BorderLayout.LINE_START);
        jPanel6.add(dcFrom, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("To");
        jPanel7.add(jLabel2, java.awt.BorderLayout.LINE_START);

        dcTo.setDefaultTime(eco.app.myswing.LabelDateChooser.DefaultTime.END_OF_DAY);
        jPanel7.add(dcTo, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7);

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout(15, 0));

        lblName.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblName.setText("Sold out");
        jPanel2.add(lblName, java.awt.BorderLayout.LINE_START);

        cbbPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbPeriodActionPerformed(evt);
            }
        });
        jPanel2.add(cbbPeriod, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.GridLayout(2, 1, 10, 0));

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Total sold out");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 7, 15));
        jPanel9.add(jLabel3, java.awt.BorderLayout.CENTER);

        lblTotalSoldOut.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblTotalSoldOut.setText("100.000 VND");
        jPanel9.add(lblTotalSoldOut, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel9);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Total income");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 7, 15));
        jPanel10.add(jLabel4, java.awt.BorderLayout.CENTER);

        lblIncome.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lblIncome.setText("100.000 VND");
        jPanel10.add(lblIncome, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel10);

        jPanel1.add(jPanel8, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 759, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbPeriodActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cbbPeriodActionPerformed
        ComboBoxItem item = (ComboBoxItem) cbbPeriod.getSelectedItem();

        DateChooseGroup.setPeriod(dcFrom, dcTo, item.getPeriod());

        Date from = dcFrom.getSelectedDate();
        Date to = dcTo.getSelectedDate();

        if (from != null && to != null) {
            filter(from, to);
        }

    }// GEN-LAST:event_cbbPeriodActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eco.app.myswing.ComboBoxCustom cbbPeriod;
    private eco.app.myswing.LabelDateChooser dcFrom;
    private eco.app.myswing.LabelDateChooser dcTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private eco.app.myswing.LabelDateChooser labelDateChooser1;
    private javax.swing.JLabel lblIncome;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTotalSoldOut;
    private eco.app.myswing.TableCustom tableCustom1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void addRow(Product product) {

        Object[] objects = EntityHelper.getData(product,
                "id",
                "name",
                "price$",
                "importPrice$",
                "sold",
                "profit$");

        tableModel.addRow(objects);

    }

    @Override
    public void fillTable(List<Product> list) {



        int totalSoldOut = 0;
        int totalProfit = 0;

        tableModel.setRowCount(0);

        for (Product product : products) {
            addRow(product);
            totalSoldOut += product.getSold();
            totalProfit += product.getProfit();
        }

        lblTotalSoldOut.setText(totalSoldOut + " Items");
        lblIncome.setText(Convertor.formatCurrency(totalProfit) + " VND");

    }

    private class ComboBoxItem {

        private int period;
        private String name;

        public ComboBoxItem(int period, String name) {
            this.period = period;
            this.name = name;
        }

        public int getPeriod() {
            return period;
        }

        public void setPeriod(int period) {
            this.period = period;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }

        @Override
        public String toString() {
            return getName();
        }

    }

}
