/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eco.app.component;

import java.awt.Component;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

import eco.app.helper.ImageHelper;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Lenovo
 */
public class Container extends javax.swing.JPanel {

    /**
     * Creates new form Container
     */
    private MigLayout layout;
    
    public Container() {
        initComponents();
        layout = new MigLayout();
        
        setLayout(layout);
        
        JLabel lblIcon = new JLabel("");
        lblIcon.setHorizontalAlignment(JLabel.CENTER);
        ImageIcon icon = new ImageHelper().openImage("big-logo.png");
        
        lblIcon.setIcon(icon);
        
        add(lblIcon, "w 100%, h 100%");
    }
    
    public void changeComponent(Component component) {
        removeAll();
        add(component, "w 100%, h 100%");
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(204, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 954, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 556, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

    }//GEN-LAST:event_formComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
