package eco.app.component;

import eco.app.model.Condition;
import eco.app.model.FilterMoldel;
import javax.swing.DefaultComboBoxModel;
import eco.app.event.FilterAcceptAction;
import java.util.List;

/**
 *
 * @author Lenovo
 * @param <E>
 */
public class FilterComponent<E> extends javax.swing.JPanel {

    private FilterMoldel<E> fillerModel;

    public FilterComponent() {
        initComponents();

        init();

    }

    private void init() {
        fillerModel = new FilterMoldel<>();

        cbbCondition.setModel(new DefaultComboBoxModel<Condition<E>>());

//        conditions = new ArrayList<>();
    }

    public void addComboBoxActionPerformer(java.awt.event.ActionListener event) {
        cbbCondition.addActionListener(event);
    }
    
    public void setAllElement(List<E> list) {
        fillerModel.setAllElements(list);
    }

    public void addCondition(Condition<E> condition) {
        DefaultComboBoxModel<Condition<E>> model
                = (DefaultComboBoxModel<Condition<E>>) cbbCondition.getModel();
        model.addElement(condition);

    }

    public void addAcceptEvent(FilterAcceptAction<E> event) {
        fillerModel.addFilterAcceptAction(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        cbbCondition = new eco.app.myswing.ComboBoxCustom();

        setMinimumSize(new java.awt.Dimension(240, 50));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(240, 50));
        setLayout(new java.awt.BorderLayout(15, 0));

        lblName.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        lblName.setText("Container");
        add(lblName, java.awt.BorderLayout.LINE_START);

        cbbCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbConditionActionPerformed(evt);
            }
        });
        add(cbbCondition, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbbConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbConditionActionPerformed
        System.out.println("Start");
        Condition<E> condition = (Condition<E>) cbbCondition.getSelectedItem();
        fillerModel.filling(condition.getCondition());
        System.out.println("End");

    }//GEN-LAST:event_cbbConditionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eco.app.myswing.ComboBoxCustom cbbCondition;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables

    public String getLabel() {
        return lblName.getText();
    }

    public void setLabel(String text) {
        lblName.setText(text);
    }

}
