/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eco.app.component;

import eco.app.helper.SaveData;
import eco.app.myswing.ButtonRandius;

/**
 *
 * @author Lenovo
 */
public class Header extends javax.swing.JPanel {

    /**
     * Creates new form Header
     */
    public Header() {
        initComponents();
        setBackground(SaveData.BG_HEADER);
    }

    public ButtonRandius getBtnShow() {
        return btnShow;
    }

    public void setBtnShow(ButtonRandius btnShow) {
        this.btnShow = btnShow;
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShow = new eco.app.myswing.ButtonRandius();

        setBackground(new java.awt.Color(121, 218, 232));
        setMaximumSize(new java.awt.Dimension(9999, 60));
        setMinimumSize(new java.awt.Dimension(433, 60));
        setPreferredSize(new java.awt.Dimension(533, 60));

        btnShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eco/app/icon/menu.png"))); // NOI18N
        btnShow.setText(" ");
        btnShow.setAlignmentX(0.5F);
        btnShow.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnShow.setMaximumSize(new java.awt.Dimension(51, 50));
        btnShow.setMinimumSize(new java.awt.Dimension(51, 50));
        btnShow.setPreferredSize(new java.awt.Dimension(51, 50));
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 474, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        
    }//GEN-LAST:event_btnShowActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eco.app.myswing.ButtonRandius btnShow;
    // End of variables declaration//GEN-END:variables
}
