/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eco.app.component;

import eco.app.entity.Product;
import eco.app.event.ProductItemListener;
import eco.app.helper.Convertor;
import eco.app.helper.ImageHelper;
import eco.app.helper.SaveData;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Lenovo
 */
public class ProductItem extends javax.swing.JPanel {

    private final Product product;
    private List<ProductItemListener> events = new ArrayList<>();

    public ProductItem(Product product) {
        this.product = product;
        initComponents();
        showProduct();
        this.add(pnPlus, BorderLayout.EAST);
        setBackground(SaveData.PRODUCT_ITEM);
        btnPlus.setRound(50);
        btnPlus.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                for (ProductItemListener evt : events) {
                    if (evt != null) {
                        evt.onClick(product, txtQuantity);
                    }
                }
                
                showProduct();
            }

        });

        txtQuantity.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent evt) {
                if (evt.getKeyCode() == KeyEvent.VK_UP) {
                    int quantity = Integer.parseInt(txtQuantity.getText());
                    txtQuantity.setText((quantity + 1) + "");
                } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                    int quantity = Integer.parseInt(txtQuantity.getText());
                    if (quantity > 1) {
                        txtQuantity.setText((quantity - 1) + "");
                    }
                }
            }
        });

        
        lblImage.setPreferredSize(new Dimension(135, 135 ));
    }

    private void showProduct() {
        lblName.setText(product.getName());
        lblPrice.setText("Price: " + Convertor.formatCurrency(product.getPrice()) + "VND");
        lblQuantity.setText("Quantity: " +( product.getQuantity() - product.getSold()));
        lblDescription.setText(product.getDescription());
        lblDiscount.setText("Discount: " + product.getImportPrice());
        lblBrandAndCategory
                .setText("Brand: " + product.getBrand().getName() + " - Category: " + product.getCategory().getName());

        try {
            Image image = ImageHelper.createImage(product.getImage(), "png");

            Image imageResize = ImageHelper.resize(image);

            lblImage.setIcon(new ImageIcon(imageResize));

        } catch (IOException ex) {
            Logger.getLogger(ProductItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void addPlusListener(ProductItemListener listener) {
        events.add(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnPlus = new javax.swing.JPanel();
        txtQuantity = new eco.app.myswing.TextFieldCustom();
        btnPlus = new eco.app.myswing.ButtonRandius();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblBrandAndCategory = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDiscount = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();

        pnPlus.setOpaque(false);

        txtQuantity.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQuantity.setText("1");
        txtQuantity.setCanEmpty(false);
        txtQuantity.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtQuantity.setRegex("[0-9]+ ");
        txtQuantity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtQuantityMouseClicked(evt);
            }
        });
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        btnPlus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eco/app/icon/plus.png"))); // NOI18N
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPlusLayout = new javax.swing.GroupLayout(pnPlus);
        pnPlus.setLayout(pnPlusLayout);
        pnPlusLayout.setHorizontalGroup(
            pnPlusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPlusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPlusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnPlusLayout.setVerticalGroup(
            pnPlusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPlusLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);

        lblName.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblName.setText("Product Item");

        lblBrandAndCategory.setFont(new java.awt.Font("Roboto", 2, 12)); // NOI18N
        lblBrandAndCategory.setText("Brand: Pessi");

        lblDescription.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        lblDescription.setText("Descriptions");
        lblDescription.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setFont(new java.awt.Font("Roboto", 2, 18)); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        lblDiscount.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        lblDiscount.setText("Discount: 5%");
        jPanel2.add(lblDiscount);

        lblQuantity.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        lblQuantity.setText("Quantity: 999");
        jPanel2.add(lblQuantity);

        lblPrice.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        lblPrice.setText("Price: 34.499 VND");
        jPanel2.add(lblPrice);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addComponent(lblBrandAndCategory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lblBrandAndCategory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);

        lblImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eco/app/icon/temp-product-item.png"))); // NOI18N
        lblImage.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        add(lblImage, java.awt.BorderLayout.LINE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtQuantityActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtQuantityActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnPlusActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnPlusActionPerformed

    private void txtQuantityMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_txtQuantityMouseClicked
        txtQuantity.selectAll();
    }// GEN-LAST:event_txtQuantityMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eco.app.myswing.ButtonRandius btnPlus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBrandAndCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JPanel pnPlus;
    private eco.app.myswing.TextFieldCustom txtQuantity;
    // End of variables declaration//GEN-END:variables
}
