package eco.app.dialog;

import eco.app.dao.CustomerDao;
import eco.app.entity.Customer;
import eco.app.entity.EntityHelper;
import eco.app.helper.MessageHelper;
import eco.app.helper.SaveData;
import eco.app.myswing.ScrollBarCustom;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class SearchCustomer extends javax.swing.JDialog {

    private Customer customerSelected;
    private List<Customer> customers = new ArrayList<>();

    /**
     * Creates new form SearchCustomer
     */
    public SearchCustomer(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        init();
        sp.setVerticalScrollBar(new ScrollBarCustom());
    }

    private void addRow(DefaultTableModel model, Customer customer) {

        model.addRow(EntityHelper.getData(customer,
                "id",
                "fullname",
                "rank",
                "phone",
                "email"
        ));

    }

    public Customer getCustomerSelected() {
        return customerSelected;
    }

    private void init() {
        try {
            customers = new CustomerDao().getAll();

            DefaultTableModel model = (DefaultTableModel) tblCustomer.getModel();

            model.setRowCount(0);

            for (Customer customer : customers) {
                addRow(model, customer);
            }

        } catch (Exception e) {
            MessageHelper.showException(this, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngSreach = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sp = new javax.swing.JScrollPane();
        tblCustomer = new eco.app.myswing.TableCustom();
        jPanel5 = new javax.swing.JPanel();
        txtSearch = new eco.app.myswing.TextFieldCustom();
        jPanel6 = new javax.swing.JPanel();
        cbFullname = new eco.app.myswing.CheckBoxCustom();
        cbID = new eco.app.myswing.CheckBoxCustom();
        jPanel3 = new javax.swing.JPanel();
        btnCancel = new eco.app.myswing.ButtonRandius();
        btnSelect = new eco.app.myswing.ButtonRandius();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(SaveData.BG_HEADER);

        jPanel2.setBackground(SaveData.BG_CONTENT);
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select a customer to add to the order");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 1, 15, 1));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout(0, 10));

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Fullname", "Rank", "Phone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomer.setOpaque(false);
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        sp.setViewportView(tblCustomer);

        jPanel4.add(sp, java.awt.BorderLayout.CENTER);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.BorderLayout(10, 0));

        txtSearch.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel5.add(txtSearch, java.awt.BorderLayout.CENTER);

        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 20));
        jPanel6.setOpaque(false);
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        cbFullname.setSelected(true);
        cbFullname.setText("Fullname");
        cbFullname.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel6.add(cbFullname);

        cbID.setText("ID");
        cbID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPanel6.add(cbID);

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 15, 5, 15));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        btnCancel.setBackground(SaveData.BTN_DANGER);
        btnCancel.setText("Cancel");
        btnCancel.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel3.add(btnCancel);

        btnSelect.setBackground(SaveData.BTN_SUCCESS);
        btnSelect.setText("Select");
        btnSelect.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        btnSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectActionPerformed(evt);
            }
        });
        jPanel3.add(btnSelect);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        customerSelected = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectActionPerformed
        int index = tblCustomer.getSelectedRow();
        int idCustomer = (int) tblCustomer.getValueAt(index, 0);
        customerSelected = (Customer) EntityHelper.find(customers, idCustomer);
        this.dispose();
    }//GEN-LAST:event_btnSelectActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        int index = tblCustomer.getSelectedRow();
        int idCustomer = (int) tblCustomer.getValueAt(index, 0);
        customerSelected = (Customer) EntityHelper.find(customers, idCustomer);
        if (evt.getClickCount() == 2) {
            dispose();
        }
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String key = txtSearch.getText().toLowerCase();
        
        DefaultTableModel model = (DefaultTableModel) tblCustomer.getModel();
        
        model.setRowCount(0);
        
        for (Customer c : customers) {
            if (c.getFullname().toLowerCase().contains(key)
                    && cbFullname.isSelected()) {
                addRow(model, c);
            } else if ((c.getId() + "").contains(key)) {
                addRow(model, c);
            }
        }
        
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SearchCustomer dialog = new SearchCustomer(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eco.app.myswing.ButtonRandius btnCancel;
    private eco.app.myswing.ButtonRandius btnSelect;
    private javax.swing.ButtonGroup btngSreach;
    private eco.app.myswing.CheckBoxCustom cbFullname;
    private eco.app.myswing.CheckBoxCustom cbID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane sp;
    private eco.app.myswing.TableCustom tblCustomer;
    private eco.app.myswing.TextFieldCustom txtSearch;
    // End of variables declaration//GEN-END:variables
}
